apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: worker-config
    literals:
      - HFTS_ENV="dev"
      - PUBSUB_EMULATOR_HOST="host.docker.internal:10005"
secretGenerator:
  - name: worker-secret
    envs:
      - secret.local.env
