apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - httproute.yaml
  - prometheus-rbac.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - ../../monitoring
  - grafana-deployment.yaml
  - grafana-service.yaml
  - renderer-deployment.yaml
  - renderer-service.yaml
